Library: Port 'Accessibility' to Python
workbenchdev/Workbench pull request #818
Opened 2023-11-18 12:20 UTC by gregorni

2023-11-18 18:14 UTC, theCapypara requested changes
on_key_released does not work:
```
TypeError: on_key_released() takes 2 positional arguments but 4 were given
```
https://docs.gtk.org/gtk4/signal.EventControllerKey.key-released.html

2023-11-18 21:53 UTC, gregorni commented
Fixed now. Thanks for the link!

2023-11-19 16:18 UTC, theCapypara approved these changes

2023-11-19 16:18 UTC, theCapypara commented
Thanks!

2023-11-19 16:18 UTC, merged